// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeWebApp.Models;

#nullable disable

namespace RecipeWebApp.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20231230104824_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeWebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Перші страви",
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Другі страви",
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Закуски",
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Салати",
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Випічка",
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Десерти",
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Гарячі супи",
                            ParentCategoryId = 1,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Холодні супи",
                            ParentCategoryId = 1,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Бульйони",
                            ParentCategoryId = 1,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Страви з м'яса",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 11,
                            Name = "Страви з риби",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 111,
                            Name = "Страви з морепродуктів",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 12,
                            Name = "Страви з овочів, грибів",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 13,
                            Name = "Страви з я'єць",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Гарнір",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 15,
                            Name = "Паста",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 16,
                            Name = "Запіканки",
                            ParentCategoryId = 2,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 17,
                            Name = "Бутерброди",
                            ParentCategoryId = 3,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 18,
                            Name = "Рулети",
                            ParentCategoryId = 3,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Паштети",
                            ParentCategoryId = 3,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Снеки",
                            ParentCategoryId = 3,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Салати з м'яса",
                            ParentCategoryId = 4,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 22,
                            Name = "Салати з риби",
                            ParentCategoryId = 4,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 222,
                            Name = "Салати з морепродуктів",
                            ParentCategoryId = 4,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 23,
                            Name = "Салити з овочів, грибів",
                            ParentCategoryId = 4,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 324,
                            Name = "Caлат з курятини",
                            ParentCategoryId = 21,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 325,
                            Name = "Caлат з cвинини",
                            ParentCategoryId = 21,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 326,
                            Name = "Caлат з яловичини",
                            ParentCategoryId = 21,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 24,
                            Name = "Млинці, оладки, сирники",
                            ParentCategoryId = 5,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 25,
                            Name = "Піца",
                            ParentCategoryId = 5,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 26,
                            Name = "Вироби з тіста",
                            ParentCategoryId = 5,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 27,
                            Name = "Торти",
                            ParentCategoryId = 6,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 28,
                            Name = "Печиво",
                            ParentCategoryId = 6,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 29,
                            Name = "Тістечка",
                            ParentCategoryId = 6,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 30,
                            Name = "Цукерки",
                            ParentCategoryId = 6,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 31,
                            Name = "Морозиво",
                            ParentCategoryId = 6,
                            RecipeCount = 0
                        },
                        new
                        {
                            Id = 32,
                            Name = "Фруктові десерти",
                            ParentCategoryId = 6,
                            RecipeCount = 0
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountOfLikes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountOfLikes = 0,
                            CreateTime = new DateTime(2023, 12, 30, 12, 48, 24, 341, DateTimeKind.Local).AddTicks(1424),
                            Rating = 5f,
                            RecipeId = 4,
                            Title = "Все вийшло, рецепт дуже класний, раджу всім!",
                            UserName = "Олег"
                        },
                        new
                        {
                            Id = 2,
                            CountOfLikes = 0,
                            CreateTime = new DateTime(2023, 12, 30, 12, 48, 24, 341, DateTimeKind.Local).AddTicks(1470),
                            Rating = 4f,
                            RecipeId = 4,
                            Title = "Спочатку трішки не вийшло з чисткою риби, але потім все зробила так як треба, чоловіку дуже сподобалось:)",
                            UserName = "Катерина"
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.CookingStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("StepIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("CookingSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = 4,
                            StepIndex = 1,
                            Title = "Для приготування рибних котлет філе минтая промиваємо холодною водою і просушуємо. Потім ріжемо на середні шматочки."
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = 4,
                            StepIndex = 2,
                            Title = "Очищаємо від лушпиння цибулю та ділимо її на дві частини."
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = 4,
                            StepIndex = 3,
                            Title = "Половину цибулі нарізаємо маленькими шматочками та смажимо до прозорості на розігрітій соняшниковій олії. Вона додасть котлетам особливої солодкості та смаку."
                        },
                        new
                        {
                            Id = 4,
                            RecipeId = 4,
                            StepIndex = 4,
                            Title = "Минтай перекручуємо разом із другою половинкою цибулі через м'ясорубку із середньою решіткою."
                        },
                        new
                        {
                            Id = 5,
                            RecipeId = 4,
                            StepIndex = 5,
                            Title = "Замочуємо в молоці скибочки білого хліба. Потім їх добре віджимаємо, перекручуємо на м’ясорубці та кладемо в рибний фарш."
                        },
                        new
                        {
                            Id = 6,
                            RecipeId = 4,
                            StepIndex = 6,
                            Title = "Додаємо у фарш куряче яйце, подрібнений свіжий кріп і смажену цибулю. Посипаємо фарш для рибних котлет сіллю та чорним перцем і рукою добре замішуємо."
                        },
                        new
                        {
                            Id = 7,
                            RecipeId = 4,
                            StepIndex = 7,
                            Title = "Щоб котлети було легше ліпити, і вони зберегли форму під час смаження, поставимо фарш у холодильник на 20-30 хвилин."
                        },
                        new
                        {
                            Id = 8,
                            RecipeId = 4,
                            StepIndex = 8,
                            Title = "Руками, змоченими в холодній воді, або за допомогою ложки, робимо з фаршу красиві однакові котлетки."
                        },
                        new
                        {
                            Id = 9,
                            RecipeId = 4,
                            StepIndex = 9,
                            Title = "Насипаємо у мисочку панірувальні сухарі й кожну котлету обвалюємо в них."
                        },
                        new
                        {
                            Id = 10,
                            RecipeId = 4,
                            StepIndex = 10,
                            Title = "Смажимо рибні котлети у розігрітій соняшниковій олії до отримання рум'яної скоринки з обох боків."
                        },
                        new
                        {
                            Id = 11,
                            RecipeId = 4,
                            StepIndex = 11,
                            Title = "Додаємо до рибних котлет на гарнір картоплю або рис і подаємо. Смачного!"
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500.0,
                            Name = "Філе минтая",
                            RecipeId = 4,
                            Unit = "гр"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 6.0,
                            Name = "Білий хліб",
                            RecipeId = 4,
                            Unit = "шматочків"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100.0,
                            Name = "Молоко",
                            RecipeId = 4,
                            Unit = "мл"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1.0,
                            Name = "Яйце куряче",
                            RecipeId = 4,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1.0,
                            Name = "Цибуля ріпчаста",
                            RecipeId = 4,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2.0,
                            Name = "Олія соняшникова",
                            RecipeId = 4,
                            Unit = "ст. л."
                        },
                        new
                        {
                            Id = 7,
                            Amount = 0.0,
                            Name = "Сіль, чорний перець, кріп",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Amount = 0.0,
                            Name = "Сухарі панірувальні",
                            RecipeId = 4
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 25,
                            CookingTime = new TimeSpan(0, 0, 40, 0, 0),
                            CreateDate = new DateTime(2023, 12, 30, 12, 48, 24, 341, DateTimeKind.Local).AddTicks(1488),
                            Description = "Оливка піца з сиром та томатним соусом - це прекрасна комбінація смаків та ароматів, яка задовольнить ваші гастрономічні бажання. Ця піца поєднує в собі солодкий смак томатного соусу, ароматний сир та інтенсивний смак оливок.\r\n\r\nПіца приготована на тонкому або товстому тісті, в залежності від вашого вибору. Тонке тісто надає піці легкість, тоді як товсте тісто робить її більш насиченою та ситною.\r\n\r\nНа тонкому або товстому коржі рівномірно розподілено томатний соус, який надає піці основний та смачний смак. Верхню частину покриває або ковбаса моцарелли, або комбінація сирів, таких як пармезан, чеддер або гауда.\r\n\r\nОсновна ідея полягає в тому, щоб нарізати оливки на тонкі кільця та рівномірно розподілити їх по всій піці. Це додає піці не тільки смак оливок, але й гарний зовнішній вигляд.\r\n\r\nПісля того, як піца випічена, на неї можна додати свіжі зелені, такі як базилік чи рукола, для додаткового аромату та свіжості.",
                            Difficulty = "Нормально",
                            Name = "Оливкова піца",
                            PhotoName = "pizza-cheese-tomatoes-olives.jpg",
                            Rating = 4.7f,
                            UserId = 1,
                            Views = 76
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 324,
                            CookingTime = new TimeSpan(0, 0, 25, 0, 0),
                            CreateDate = new DateTime(2023, 12, 30, 12, 48, 24, 341, DateTimeKind.Local).AddTicks(1494),
                            Description = "Шеф-салат - це вишукана та смачна страва, яка зазвичай подається в ресторанах як підкреслення кулінарної майстерності шеф-кухаря. Одним із класичних варіантів є \"Цезар\", який являє собою комбінацію свіжих листків салату, курячого філе, гартованого яйця, гарячого бекону, пармезану та ароматного соусу.\r\n\r\nОсновні складники шеф-салату можуть варіюватися залежно від рецепту та кухні, але зазвичай вони включають в себе свіжі овочі, м'ясо або рибу, сир, гарнір та соус.",
                            Difficulty = "Легко",
                            Name = "Шеф-салат",
                            PhotoName = "chef-salad.jpg",
                            Rating = 3.8f,
                            UserId = 1,
                            Views = 43
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 27,
                            CookingTime = new TimeSpan(0, 1, 20, 0, 0),
                            CreateDate = new DateTime(2023, 12, 30, 12, 48, 24, 341, DateTimeKind.Local).AddTicks(1498),
                            Description = "Шоколадний торт з полуницями - це чудовий десерт, який поєднує в собі солодкість шоколадного бісквіта з ароматом свіжих полуниць.",
                            Difficulty = "Складно",
                            Name = "Шоколадний тортик з полуницями",
                            PhotoName = "chocolate-cake.jpg",
                            Rating = 4.3f,
                            UserId = 1,
                            Views = 58
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 11,
                            CookingTime = new TimeSpan(0, 1, 0, 0, 0),
                            CreateDate = new DateTime(2023, 12, 30, 12, 48, 24, 341, DateTimeKind.Local).AddTicks(1501),
                            Description = "Рибні котлети – це ароматна, неймовірно смачна та дієтична страва. Вони на тривалий час насичують організм, ідеально поєднується з різноманітними гарнірами та соусами. Ніжні рибні котлети стануть чудовою альтернативою звичайній смаженій рибі.",
                            Difficulty = "Нормально",
                            Name = "Рибні котлети",
                            PhotoName = "rybni-kotlety.jpg",
                            Rating = 4.5f,
                            UserId = 1,
                            Views = 22
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "artem@gmail.com",
                            Name = "Артем",
                            Password = "12345678",
                            Surname = "Бабенко"
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.Category", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Comment", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.CookingStep", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Recipe", "Recipe")
                        .WithMany("CookingSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Ingredient", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeWebApp.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Category", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CookingSteps");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RecipeWebApp.Models.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
